In [1]:
import pandas as pd

1. Load the Data

In [2]:
df = pd.read_excel('Customer Call List.xlsx')

In [3]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         21 non-null     int64
 1   First_Name         21 non-null     object
 2   Last_Name          20 non-null     object
 3   Phone_Number       19 non-null     object
 4   Address            21 non-null     object
 5   Paying Customer    21 non-null     object
 6   Do_Not_Contact     17 non-null     object
 7   Not_Useful_Column  21 non-null     bool
dtypes: bool(1), int64(1), object(6)
memory usage: 1.3+ KB

2. Remove Duplicates

In [5]:
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

3. Drop Unnecessary Columns   
Dropping 'Not_Useful_Column' as it adds no value to the analysis

In [6]:
df = df.drop(columns='Not_Useful_Column')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

4. Clean String Columns (Last Name)   
Strip unwanted punctuation from the Last_Name column

In [7]:
df['Last_Name'] = df['Last_Name'].str.strip("123._/")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

5. Standardize Yes/No Columns

In [8]:
yes_no_mapping = {'Yes': 'Y', 'No': 'N'}
df['Paying Customer'] = df['Paying Customer'].replace(yes_no_mapping)
df['Do_Not_Contact'] = df['Do_Not_Contact'].replace(yes_no_mapping)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,N,Y
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y
6,1007,Jeff,Winger,NaN,1209 South Street,N,N
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Y,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Y,N
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Y
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N

6. Clean and Format Phone Numbers
Remove all non-alphanumeric characters

In [9]:
df['Phone_Number'] = df['Phone_Number'].replace('[^a-zA-Z0-9]', '', regex=True)
# Convert to string to allow string slicing 
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: str(x))
# Format as XXX-XXX-XXX
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:9])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Y,N
1,1002,Abed,Nadir,123-643-977,93 West Main Street,N,Y
2,1003,Walter,White,706-695-039,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Y,Y
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,N
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Y,Y
6,1007,Jeff,Winger,nan--,1209 South Street,N,N
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,N
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Y,NaN
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Y,N
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,N
11,1012,Harry,Potter,706-695-039,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-234,2039 Main Street,Y,N
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Y,N
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,N,N
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,N,N
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Y,N
17,1018,Clark,Kent,706-695-039,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na--,N/a,N/a,Y
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Y,N

7. Parse Address Column

In [10]:
# Split the address column into Street, State, and Zip Code
df[['Street_Address', 'State', 'Postal_Code']] = df['Address'].str.split(',', n=2, expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Postal_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-977,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,White,706-695-039,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,nan--,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-039,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-234,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-039,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,Na--,N/a,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

8. Handle Missing/Null Values

In [11]:
df['Phone_Number'] = df['Phone_Number'].str.replace('nan--', '')
df['Phone_Number'] = df['Phone_Number'].str.replace('Na--', '')
df = df.fillna('')

df['Address'] = df['Address'].str.replace('N/a', '')
df['Paying Customer'] = df['Paying Customer'].str.replace('N/a', '')
df['Street_Address'] = df['Street_Address'].str.replace('N/a', '')

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Postal_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-977,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,706-695-039,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-039,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-234,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-039,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

10. Drop row where "Do_Not_Contact" is Y

In [12]:
for x in df.index:
    if df.loc[x, 'Do_Not_Contact']=='Y':
        df.drop(x, inplace=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Postal_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-039,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-039,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-234,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-039,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

11. Drop row "Phone_Number" is empty

In [13]:
for x in df.index:
    if df.loc[x, 'Phone_Number']=='':
        df.drop(x, inplace=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Postal_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-039,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Y,N,25th Main Street,New York,
11,1012,Harry,Potter,706-695-039,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-234,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-039,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

12. Replace Empty Do_Not_Contact with 'N'

In [14]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].replace('', 'N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Postal_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-039,298 Drugs Driveway,N,N,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Y,N,25th Main Street,New York,
11,1012,Harry,Potter,706-695-039,2394 Hogwarts Avenue,Y,N,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-234,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-039,3498 Super Lane,Y,N,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

13. Reset Index

In [15]:
df.reset_index(drop=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Postal_Code
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1003,Walter,White,706-695-039,298 Drugs Driveway,N,N,298 Drugs Driveway,,
2,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,N,123 Dragons Road,,
3,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,N,98 Clue Drive,,
4,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Y,N,25th Main Street,New York,
5,1012,Harry,Potter,706-695-039,2394 Hogwarts Avenue,Y,N,2394 Hogwarts Avenue,,
6,1013,Don,Draper,123-543-234,2039 Main Street,Y,N,2039 Main Street,,
7,1014,Leslie,Knope,876-678-346,343 City Parkway,Y,N,343 City Parkway,,
8,1015,Toby,Flenderson,304-762-246,214 HR Avenue,N,N,214 HR Avenue,,
9,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
10,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
11,1018,Clark,Kent,706-695-039,3498 Super Lane,Y,N,3498 Super Lane,,
12,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

14. Export Cleaned Data

In [16]:
df.to_csv("Cleaned_Customer_Call_List.csv", index=False)
print("Data cleaning completed successfully.")

Data cleaning completed successfully.